blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://github.com/mobxjs/mobx/issues/new/choose
    about: This repo will be archived soon. Please use this link to create an issue in mobx repo.
  - name: Documentation
    url: https://mobx.js.org
    about: Official Mobx documentation 
  - name: GitHub discussions
    url: https://github.com/mobxjs/mobx/discussions    
    about: We are open to your questions or discussion
  - name: StackOverflow
    url: https://stackoverflow.com/questions/tagged/mobx
    about: We are open to your questions or discussion
